version: '3.8'
services:
  database:
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: btre
  static:
    image: nginx:latest
    volumes:
      - static:/usr/share/nginx/html/static
    ports:
      - "80:80"
      - "443:443"
  btre-web:
    image: btre-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SUPERUSER_USERNAME: root
      DJANGO_SUPERUSER_PASSWORD: p@5$w0rD
    ports:
      - "8000:8000"
    depends_on:
      - database
      - static