# Generated by Django 5.2.6 on 2025-10-13 19:14

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zipcode', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.DecimalField(decimal_places=1, max_digits=6)),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('exterior_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Exterior')),
                ('interior_photo_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Interior Photo 1')),
                ('interior_photo_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Interior Photo 2')),
                ('interior_photo_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Interior Photo 3')),
                ('interior_photo_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Interior Photo 4')),
                ('interior_photo_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Interior Photo 5')),
                ('interior_photo_6', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Interior Photo 6')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photo')),
                ('description', models.TextField(blank=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField()),
                ('is_mvp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Realtor',
                'verbose_name_plural': 'Realtors',
                'db_table': 'realtors',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_title', models.CharField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btre.listing')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='btre.realtor', verbose_name='Realtor'),
        ),
    ]
