# Generated by Django 6.0.7 on 2026-07-22 17:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior_photo_1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Interior Photo 1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior_photo_2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Interior Photo 2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior_photo_3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Interior Photo 3'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior_photo_4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Interior Photo 4'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='btre.realtor', verbose_name='Realtor'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='description',
            field=models.TextField(),
        ),
    ]
